### ISSUE TITLE
sous-titres

### ISSUE THREAD

**Issue by parmentelat** [parmentelat/flotpython#35]
Pour le suivi au long cours de cette opération sous-titres, je vous propose de migrer sur github

* la page wiki sur FUN est vide, utilisez maintenant 
https://github.com/parmentelat/flotpython/wiki/SubTitles à la place
* et utilisez maintenant le présent canal plutôt que le fil dans le forum sur fun-mooc.fr (que je vais  fermer)

Ce sera plus sûr, car je ne vais plus aller trop souvent sur le cours de fUN, alors que si vous écrivez ici je recevrai un mail

**Comment by parmentelat** [comment]
@Papisido

le flot normal lorsqu'on travaille avec git(hub), c'est comme ceci:

* 1er cas (cf. moocpython): les participants ont les droits d'accès dans le repo; alors là c'est simple, on n'a qu'à cloner le repo depuis gihub, faire des changements dedans, repousser.

* 2ème cas (cf. flotpython): les participants n'ont pas les droits d'accès; c'est le mode 'normal' lorsqu'on travaille en groupe, je ne connais pas a priori les gens qui ont des vélléités à contribuer, ou je n'ai pas forcément envie de donner les droits en écriture

dans ce cas-là, le flot c'est que le contributeur crée un fork (un clone mais sur github, dans lequel il a les droits en écriture) et dans lequel il peut pousser ses modifications; ça permet comme ça de les exposer en lecture
ensuite le contributeur va dans le repo officiel et crée un pull request; les deux points qu'on donne sont (*) la branche dans laquelle on veut pousser (typiquement la branche master du repo officiel) et la branche dans laquelle se trouve le code à pousser (typiquement la branche master du fork du contributeur)

je comprends que c'est une gymnastique qui peut paraître tarabiscotée au début; par contre l'idée de passer par moocpython pour me faire passer du contenu qui se rattache à flotpython, ça ça m'a bien perturbé, j'ai eu du mal à suivre !! aussi je suis surpris 

mais bon sinon envoyez-moi tout simplement un mail :)

**Comment by Carine07** [comment]
Juste pour vous prévenir que les [vidéos mises sous youtube](https://www.youtube.com/channel/UCIlUBOXnXjxdjmL_atU53kA/) n'utilisent pas les fichiers de sous-titres créés. 

A la place, il y a des sous-titres "générés" par google. C'est plutôt bluffant, même si certains mots ne sont pas reconnus (emacs devient maxou, idle ido, etc.) et s'il y a des fautes d'accord. La voix d'Arnaud est mieux reconnue. Il faudrait voir si, avec un micro-casque, la qualité de la reconnaissance vocale s'améliore. Google utilise le format [scc ](https://support.google.com/youtube/answer/2734698?hl=fr&ref_topic=7296214) (Scenarist Closed Caption), mais accepte aussi la version de base de srt sans info de style en UTF-8.

Si votre ingé pédagogique (Aurélie?) souhaite mettre "nos" fichiers de sous-titres, voici le [lien](https://support.google.com/youtube/answer/2734796?hl=fr) qui explique comment faire.

Il est possible de [modifier les sous-titres générés](https://support.google.com/youtube/answer/6373554) pour les corriger dans le gestionnaire de vidéos de youtube. Par contre, il semble être impossible de les exporter avec youtube.

**Comment by Carine07** [comment]
Récap des 3 façons pour sous-titrer un cours:

1. Utiliser un outil pour ajouter des sous-titres à une vidéo (format de sortie .srt)
Par exemple, [http://subtitle-horse.com](http://subtitle-horse.com) ou, sous linux, gnome-subtitle

2.  Utiliser un outil de reconnaissance vocale pour récupérer le texte brut, puis un outil d'ajout de sous-titres pour synchroniser le texte à la vidéo.
Sous Chrome, pour la reconnaissance vocale, il existe [https://speechnotes.co/fr/](https://speechnotes.co/fr/) ou alors il faut créer un document sous google drive, puis dans le menu tools (outils), choisir voice typing (dictée vocale?? en français).
Auparavant, pour que cela fonctionne, il faudra configurer les outils d'enregistrement (recording devices) pour que le mixage stéréo soit l'outil par défaut et non les micros (comme expliqué dans cette [vidéo ](https://www.youtube.com/watch?v=erx9czQsY2Q) pour mac ou windows) 
Après pour synchroniser le texte à la vidéo, il est possible d'utiliser les outils décrits en 1) ou bien, si la vidéo est sur youtube, de laisser youtube la [synchroniser automatiquement](https://support.google.com/youtube/answer/2734796?hl=fr).

3. Si la vidéo est sous youtube, utiliser les sous-titres générés pour les corriger
Youtube ne permet pas de les exporter. J'ai utilisé le site [https://fr.keepvid.com](https://fr.keepvid.com), mais il y en a d'autres, pour récupérer le fichier srt. Sous notepad++ ou emacs, il est possible d'enlever les balises \<font\>\<\/font\> qui ne servent pas. Il y a juste des problèmes de synchronisation. 
Voici, par exemple, le fichier [w9-s2-av.fr.srt](https://github.com/Carine07/flotpython/blob/master/w9/w9-s2-av.fr.srt) généré (à partir de la vidéo sur les décorateurs) à utiliser sur ce [site ](http://subtitle-horse.com/subtitleVideo?url=https://d381hmu4snvm3e.cloudfront.net/videos/DdppgsIkRkqb/LD.mp4) pour voir ces problèmes.  

Cette dernière solution permettrait de mettre, très rapidement, les sous-titres à toutes les vidéos sous fun, pour l'accessibilité,. Il faudrait juste corriger les fautes d'orthographe et les mots non reconnus. Tant pis, si le texte est légèrement en retard sur la vidéo. Faire le recalage serait chronophage.

**Comment by parmentelat** [comment]
Merci pour cette suggestion; toutefois comme l'a mentionné Isabelle, et pour avoir fait un peu ce travail dans le passé, il me semble préférable de faire le travail entièrement à la main. En effet pour obtenir un résultat de la même qualité en partant d'un traitement automatique, on se rend vite compte qu'on y passe au moins autant de temps (voire plus, cf. la synchro) et le travail est encore plus rébarbatif ! :)

**Comment by Carine07** [comment]
Ok, j'essayerai peut-être la solution 2 (texte généré sans la synchro, puis copier-coller pour la création du fichier de sous-titres).
Pouvez-vous, @parmentelat  ou @AureliestaffTMA , nous dire si: 
1. il y a des vidéos qui vont être refilmer pour la prochaine session (pour éviter de les sous-titrer)? 
2. "nos" sous-titres seront intégrés aux vidéos sur youtube, au lieu d'utiliser les sous-titres automatiques (cela donnerait encore plus de sens à notre démarche)
merci
FYI @deladan @jgorene

**Comment by parmentelat** [comment]
Oui il se peut qu'on retourne la semaine 7 - cette année on a fait une vidéo un peu bouche-trou histoire de dire qu'il y en avait une mais bon; il se peut tout à fait qu'on ne fasse qu'en ajouter en fait, c'est à voir
Le reste par contre je ne pense pas qu'on retourne...

S'agissant d'exposer les sous-titres de ce repo github sur youtube: je vais en parler mais je ne pense pas qu'on va l'envisager, en tous cas pas s'il faut les ajouter au fur et à mesure; on verra une fois qu'on aura des gros morceaux comme plusieurs semaines entières. Je ne me rends pas bien compte du travail que ça représente en fait.

**Comment by Carine07** [comment]
Les sous-titres de w7 ont déjà été faits. Pas grave.
Je pense que cela demande moins de 3 minutes par vidéo de rajouter le fichier de sous-titre (cf [ici](https://support.google.com/youtube/answer/2734796?hl=fr))
Après il faudrait aussi les traduire en anglais :)

**Comment by arnaudlegout** [comment]
Le 07/02/2018 à 10:52, Carine07 a écrit :
>
> Ok, j'essayerai peut-être la solution 2 (texte généré sans la synchro, 
> puis copier-coller pour la création du fichier de sous-titres).
> Pouvez-vous, @parmentelat <https://github.com/parmentelat> ou 
> @AureliestaffTMA <https://github.com/aureliestafftma> , nous dire si:
>
>  1. il y a des vidéos qui vont être refilmer pour la prochaine session
>     (pour éviter de les sous-titrer)?
>  2. "nos" sous-titres seront intégrés aux vidéos sur youtube, au lieu
>     d'utiliser les sous-titres automatiques (cela donnerait encore
>     plus de sens à notre démarche)
>     merci
>     FYI @deladan <https://github.com/deladan> @jgorene
>     <https://github.com/jgorene>
>

oui, je pourrai m'en charger.

Cordialement,
Arnaud.

**Comment by Carine07** [comment]
C'est bien car la version générée des sous-titres est parfois incorrecte (par exemple, sur le mot callable dans w9-s2, cf. le [diff ](https://github.com/parmentelat/flotpython/pull/44/commits/e78df863c9e2dc26fe93acb2ae29137e3cd5624a) entre version générée et version transcrite).

@parmentelat 
Désolée pour mes caractères DOS qui "polluent" (j'ai vu l'action dos2unix'ed all srt files)

**Comment by parmentelat** [comment]
Pour rappel la chaine youtube est ici

https://www.youtube.com/channel/UCIlUBOXnXjxdjmL_atU53kA/

**Comment by Carine07** [comment]
HS youtube

Je suis loin d'être une spécialiste, mais je pense qu'il manque un peu d'éléments de navigation entre vos différentes playlists. Par exemple, quand on finit la vidéo [1.6](https://www.youtube.com/watch?v=ii7BpItiOeM&list=PL2CXLryTKuwwoPO9s_fd5a4eRoWgHhrKT&index=6) de la playlist 1, il ne propose pas la vidéo 2.1 ou la playlist 2. Il faut "remonter" en cliquant sur le nom de la chaîne, Cours Python 3, (pas sûre que tout le monde le fasse) pour changer de playlist. Si on "arrive" sur une vidéo (ex: [8.2](https://www.youtube.com/watch?v=NvR7lpC61g0)) sans passer par une de vos playlists, ce n'est pas sûr que la vidéo suivante (8.3) et la précédente (8.1) soient proposées, ou bien la playlist suivant (9) ou la précédente (7).
Il faudrait peut-être rajouter un [écran de fin ](https://support.google.com/youtube/answer/6388789?co=GENIE.Platform%3DDesktop&hl=fr) à votre vidéo avec max quatre éléments (vidéo précédente, vidéo suivante, retour à la chaîne, playlist suivante, playlist précédente, les MOOCs INRIA, FUN, etc.). Mettre aussi des liens vers ces éléments, dans la description de la vidéo, ainsi que des mots clés.
Peut-être aussi mettre des [fiches](https://support.google.com/youtube/answer/6140493?hl=fr&ref_topic=6140492), pour mettre un lien vers une vidéo où vous avez présenté la notion, vers ipython.org, etc. ou un sondage pour rendre la vidéo plus interactive et avoir un petit feedback.

**Comment by parmentelat** [comment]
Il va nous falloir discuter licences et crédits sur ce sujet.

@Carine07  et @PapiSido pourriez-vous svp me contacter directement par mail, je n'ai pas d'adresse directe pour vous joindre, merci d'avance

**Comment by Carine07** [comment]
Les sous-titres à vérifier pour la prochaine session car j'ai décidé de corriger les sous-titres pour que les explications soient correctes (enfin si j'ai bien compris et que je ne me trompe pas).

w9-s4
3:25 j'ai mis "catégorie classe (NDLR pas type)."
4:47 j'ai mis " super-classe (NDLR pas sous-classe)." comme dans le powerpoint derrière, et puis il corrige en 5:10
6:18 "primitives" (au lieu de primitifs) car comme en 5:30 et en 14:06
8:26, 8:49 "reset_x" (au lieu de reset) car reset_x dans le code montré.

w9-s5
4:41 j'ai mis "un attribut (NDLR il a dit argument mais ce n’était pas le bon mot)" car rectifié après par @arnaudlegout
7:03 "\_\_delete\_\_" (au lieu de \_\_del\_\_) pour les méthodes des descripteurs
7:59 "la classe (NDLR pas l'objet)" car rectification juste après.

**Comment by parmentelat** [comment]
Les sous-titres sont à présent complets, à nouveau merci à tous les contributeurs et particulièrement Isabelle Poirier :)

Je ferme ce ticket, et je vous dis à la prochaine session !

Bien cordialement -- Thierry

**Comment by Carine07** [comment]
Juste pour conserver, ici, le petit tutoriel d'utilisation de [http://subtitle-horse.com/](http://subtitle-horse.com/) (utile pour créer des sous-titres à une vidéo, sans rien installer) que j'avais écrit sous FUN, au cas où.
@deladan (Isabelle Poirier) qui a écrit 80% des sous-titres a utilisé gnome-subtitle, sous linux.

En fait, je lance la vidéo (partie gauche), puis arrête la vidéo avec barre d'espace au premier mot de la narration, et clique sur **add at current time** qui crée le premier sous-titre à droite. Après, je n'utilise que les actions/boutons des sous-titres (surtout le bouton **play title**) de la partie droite (pour éditer un sous-titre, **double-cliquer** dessus ou taper **e**).

Le raccourci clavier **ctrl+o** est le plus utile pour remplacer le temps de fin du sous-titre courant par le temps courant (possible aussi de le faire avec la **petite flèche** devant le temps) et ajuster le nouveau temps de début du sous-titre suivant (si ce dernier n'existe pas, il est créé). **F9** est aussi utile si vous voulez scinder votre sous-titre édité à l'endroit où se trouve le curseur (possible aussi de le faire avec le menu contextuel); après il faudra recaler les deux-titres par rapport à la vidéo.
